language: perl
perl:
    - "5.22"
    - "5.20"
    - "5.18"
script: prove t/
before_install: 
    - sudo apt-get update -q
    - sudo apt-get install -q libmoose-perl
install:
    - cpanm MooseX::ABC String::Trim Readonly List::Compare.pm Clone Test::Exception Array/Utils.pm String/Numeric.pm MooseX::ClassAttribute Log/Log4perl.pm MooseX/StrictConstructor.pm
